name: Run Script Every 24 Minutes

on:
  schedule:
    - cron: '*/24 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright

      - name: Install Playwright Browsers
        run: |
          python -m playwright install

      - name: Run script with Xvfb (Headed Mode)
        run: |
          xvfb-run -a python Auto-wal.py  # Use xvfb-run to simulate a display
